spring:
  application:
    name: Highlighter-demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(7F1Bp5SlS2Rl5479lpalVkpQcpfxWLXM90N/pNsEUPBBiSjT1z0xGC1HKM20z30R)
    username: ENC(+yxTEYFjQCYMayzjU6B8SA==)
    password: ENC(+yxTEYFjQCYMayzjU6B8SA==)
    username: ENC(2qVMa/bR8rFXQL47+rsVbA==)
    password: ENC(2qVMa/bR8rFXQL47+rsVbA==)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
#  sql:
#    init:
#      platform: mariadb
#      mode: always
#      data-locations: classpath:/data.sql
  profiles:
    include: jwt
    active: test
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:
      credentials:
        access-key: ENC(Co4tUU9fO2RDhJ+9DdoOiWfx2tn+tljRAtXS2Vqx+oY=)
        secret-key: ENC(9xC0pO3q89PJZ4K2uzOSyAaG6PgtS/CDI2dxn7h3dmTlu80txCjiPvvyMlw3pKnuOuwuZJeZYSM=)
      region:
        static: ap-northeast-2
      s3:
        bucket: highl-file
    openfeign:
      circuitbreaker:
        enabled: true
      httpclient:
        hc5:
          enabled: true
          connection-request-timeout: 5

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none


server:
  port: 8081
  error:
    include-stacktrace: always

riot:
  api: RGAPI-afd067ab-e757-4275-a4ae-9ae89607bb23

logging:
  level:
    org.example.highlighterdemo.feign: DEBUG




